auto detect nuget packages
amdigital-co-uk/workflows pull request #33
Opened 2024-08-07 13:22 UTC by mjelic111

# Overview

project list is getting longer and longer and hard to maintain AB#20810

# Version updates

Is it a MAJOR version bump. Project input string is automatically detected using bash script.

2024-08-07 14:53 UTC, 91dave requested changes
If possible, it would be ideal to avoid needing a MAJOR version change, but I think there is a fairly simple tweak we can make.

Start off by re-instating the `projects` input, but make it non required, with a default of empty string.

Then in the script for the build step you can test to see if it's empty, then only auto-detect if true, otherwise use the user-provided list. Something like this could help:

```bash
projects="${{ inputs.projects }}"

if [ -z "$projects" ] # if the string is zero length
then
    # code to auto-detect projects
fi

for project in $projects #etc
```

If this approach can be made to work, it keeps the new version backwards-compatible, meaning we can get away with a MINOR change.

2024-08-08 09:15 UTC, 91dave reviewed
@budecevicm @mjelic111 you might need to also set `projects` to be `required: false`

2024-08-08 09:31 UTC, mjelic111 commented
> @budecevicm @mjelic111 you might need to also set `projects` to be `required: false`

Yes, it must be required set to false, sry for that

2024-08-08 10:24 UTC, 91dave approved these changes

2024-08-08 11:06 UTC, merged